services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./files:/app/files
    environment:
      - OLLAMA_SERVER_MODE=local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 60s
      retries: 3

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - FILES_DIR=/app/files
      - VECTORSTORE_DIR=/app/chroma_db
      - AZURE_KEYVAULT_NAME=team3chatbot
      - AZURE_SECRET_NAME=ollama-private-key
    volumes:
      - ./files:/app/files
      - ./chroma_db:/app/chroma_db
