services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./id_ed25519:/root/.ollama/id_ed25519
      - ./files:/app/files
    environment:
      - OLLAMA_SERVER_MODE=local
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 30s
      timeout: 10s
      retries: 3

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_KEY_PATH=/root/.ollama/id_ed25519
      - FILES_DIR=/app/files
      - VECTORSTORE_DIR=/app/chroma_db
    volumes:
      - ./files:/app/files
      - ./id_ed25519:/root/.ollama/id_ed25519
      - ./chroma_db:/app/chroma_db